import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { UserProvider } from "@/contexts/userContext";
import { ThemeLayoutWrapper } from "@/components/theme-layout-wrapper";
import { PermissionsProvider } from "@/contexts/permissionsContext";
import { PreloadPermissions } from "@/components/preload-permissions";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Zapllo CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive" // Ensures the script loads before your app's JavaScript
          async
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeLayoutWrapper>
          <NextTopLoader />
          <UserProvider>
            <PermissionsProvider>
              {/* Add this component to preload permissions */}
              <PreloadPermissions />
              {children}
            </PermissionsProvider>
          </UserProvider>
        </ThemeLayoutWrapper>
      </body>
    </html>
  );
}